### ISSUE TITLE
Review current method for adding fields to the data dictionary for a dataset

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#110]
**OP timer**: <https://openplus.monday.com/boards/4092908516/pulses/4885620989>

## Issue

Data Dictionary is a list of fields associated with a data set. Each field has meta data of its own.

There could be anywhere from a dozen to 800 rows in a data set. Most columns are using text input, three of the columns use entity references to taxonomy terms. See the list at `/admin/structure/paragraphs_type/data_column/fields`.

Currently, we are using the paragraphs module to do this, with an option to import using csv.

There are a few issues with this approach:

1. Error, When testing with 100 rows, when edit all is selected, then *collapse all* , you get the error
   > An unrecoverable error occurred. The uploaded file likely exceeded the maximum file size (8 MB) that this server supports.
2. Performance, with only 100 rows, it takes several seconds to open all the rows for editing.
3. UI, Paragraphs has an awkward UI.

We have not investigated the impact using paragraphs has on the database and overall performance. With thousands of data sets, and potentially hundreds of rows for each one, this could be significant.

### Get rid of paragraphs and use an xlsx import

This would work similar to the csv import. The xlsx file would be made available as a downloadable template. We can build it so that the template has select lists for the items currently using entity references. The user fills out the spreadsheet and uploads it.  Then we use [csv file formatter](https://www.drupal.org/project/csvfile_formatter) to render data tables. For updates, the user would download the xlsx file, make the changes and upload it. With this approach, we would remove the fields from the database and the data would come from the file. If search abilities on the data dictionary are needed, we can connect the data file to Solr directly. In the Drupal search, the user would not know the difference.

Issues with this approach

1. We lose the connection to the taxonomy in Drupal. So the three fields currently using entity references would need to be a select list in the Excel sheet. This needs to be maintained by somebody.
2. There is no way for an author to know if they are using the correct template. For example, January 1, 2024 a user downloads the template, adds values and uploads to a data-set. February 1, 2024 an administrator adds new values and changes the existing value in the excel template. March 1, 2024 the user needs to make a change so they download a copy of the xlsx file attached to the data set, make their change and upload it. There is no way for the user to know that there have been changes made to the template.
3. There is no way to search on values in the data dictionary at a site wide level. We would need to connect the file to Solr.
4. With this approach, there is no way for a user to change a row in the UI. We don't know yet if that is an issue or not.

### Keep using paragraphs

Keep doing what we are doing, but remove the 'edit all' option on the build page. We need to understand performance and DB issues in doing this.

## Task description

Investigate the options for getting a high volume of row into the data set. Assume 100 rows for testing and evaluation.

1. What is the impact on users of paragraphs vs file formatter. Consider users posting data and users looking for data.
2. What is the impact on the system in terms of database, performance, etc.
3. How future proof is it? What happens if changes are made to a field currently using an entity reference to a taxonomy?
4. What is the level of effort if we change from what we have now? We don't want to spend 2 or 3 sprints solving this to the detriment of the rest of the project.

## Deliverable

Make a recommendation of the best path forward. Explain why you made this decision and identify the pros and cons of the proposed solution.

**Comment by NicoledeGreef** [comment]
Power Users have indicated that APIs to pipe data into the catalog would be preferable but that is not helpful to mainstream business users so this is something to explore as well.

**Comment by lkmorlan** [comment]
**Recommendation:** Continue with the current system for now. Obtain feedback from users as they try out the system under development. If problems are found in the current system or opportunities identified, make changes at that time. Remove the "Edit all" button and make any other UI tweaks that seem reasonable.

We already have a system that works. There is no clear case at this time for moving to a different system. So, we should continue with what we have instead of investing in changing it until such time as there is a clear case for a change.

There could be UI tweaks to paragraphs that would make it easier to use with large numbers of columns.

The main problem identified with paragraphs relates to the "Edit all" button not working correctly. This button is not needed and can easily be removed with a form alter.

The paragraphs-based solution is more flexible than other solutions. It allows importing a complete dataset from a source file. This is easier for advanced users and large numbers of columns. It also allows using the UI to create a dataset from scratch or to make edits. This is easier for smaller datasets, less experienced users, or situations were a small edit is needed. It may be cumbersome to download a spreadsheet, edit, and re-upload just to fix a typo.

The data storage method and UI should not have any impact on users looking for data. It ought to be possible to create the desired UI either way. A UI that requires interacting with data based on the details of the column data could be more difficult to implement in a system based on csvfile_formatter because the data cannot be easily queried.

The paragraphs-based solution would be more taxing on the database. Display or editing of a dataset columns requires the paragraphs software to load the column metadata. A system based on csvfile_formatter does not touch the database at all. It would likely require more processing on display since the file needs to be parsed and formatted each time. As well, search could be more complicated. There needs to be a mechanism for getting the file data into Solr.

If there is a desire to quantify performance, that should be done once there is a candidate implementation on the infrastructure that will be used for production. Sample data could be generated and manipulated under typical workloads. Running performance tests on infrastructure that is not like what production will be like could give misleading results, though it could be useful for comparing the relative performance of different solutions.

The paragraphs-based solution can use the existing Drupal system for managing revisions. A using csvfile_formatter would mean either not tracking revisions or coming up with a custom way to do it.

Using csvfile_formatter would create challenges for fixed-value fields. If editing means downloading the current file, changing it, and re-uploading it, then there would be no way to add options to fixed-value fields. If there are good tools for generating spreadsheet files, it could be setup so that downloading gives not the original uploaded file, but a file generated using current defaults and the values from the original file. This would allow adding options to fixed-value fields.

It would be several days of work to implement use of csvfile_formatter. How much would depend on the capabilities of the module, exactly what we want it to do, and how difficult it is to integrate with Solr, in particular, exposing values within the uploaded file as a search facet.

If the basic approach of paragraphs is desired but it is found to be too taxing on the database, another option would be to store the column data in a separate set of database tables with a schema specifically designed for this use case. This allows optimal use of database resources. This would require custom implementation to handle integration with Solr and revisioning.

It should not be difficult to create an API to the paragraphs-based solution. Drupal has built-in API tools. Making this work with csvfile_formatter would be more difficult. An API call to update the columns would have to result in the generation of a spreadsheet file which is then treated as if it had been uploaded.

**Comment by CraigClark** [comment]
I'm good with this. I'll write up a couple of related issues then close it.
