### ISSUE TITLE
does Drupal as implemented in the Finance Data Catalogue support the storage and display of Indigenous characters?

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#126]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/question

---

## What's your Question?
There is a draft Indigenous Languages Data Standard (draft v0.3) and Guidelines that provide more information on assessing.  The standard indicates that new applications/systems must address this need upfront.  The guidelines provide more info on what this entails:

https://www2.qa.gov.bc.ca/gov/content/data/including-indigenous-languages-in-government-records-systems-services/how-to-support-indigenous-languages-in-systems

**Comment by CraigClark** [comment]
@NicoledeGreef 

This came up in the kick-off meeting that BC will include indigenous languages in the future. All the technical specifications in the guide you posted are met. When we write code, any strings are wrapped in what Drupal calls a _T string_. This is so that if we ever need to translate something in the future, we can. The Base build theme uses BC sans.

Beyond supporting characters, Drupal does a great job with multi-lingual sites.

Here is an example of Inuktitut in your cloud environment.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/d7017181-fff8-4f57-b064-80cf7366eee2)
