### ISSUE TITLE
Document roles and permissions

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#219]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5450162443

---

**Comment by CraigClark** [comment]
@NicoledeGreef 

>[!NOTE]
> As an editor, I can currently delete MRs I create, including published records. Is this the behaviour we want?
> We could do the following:
>  - DC editor: delete MR that has never been published, unpublish own published MR's if the org matches
>  - DC manager: delete MR that has never been published, unpublish any published MRs in their org
> - DC admin: delete anything, unpublish anything
>  

I'll assign this to you until I know what the permissions need to be

**Comment by NicoledeGreef** [comment]
^^^makes sense.  Thanks!

**Comment by mjmcclung** [comment]
For consideration:  MR's are likely considered a 'record' in an IM sense, so proper information destruction protocol would apply.  The IM team should be involved in this discussion, especially for published records.  Also, in conversation with CIRMO folks we've been told to consider "data documentation" (i.e. Metadata Records) as **unscheduled** records, which means they can't be deleted without the approval of the government Chief Records Officer since they don't currently have an associated Information Schedule.

**Comment by NicoledeGreef** [comment]
We will add the IM/Records concerns to the Catalogue Admin User documentation.

> For consideration: MR's are likely considered a 'record' in an IM sense, so proper information destruction protocol would apply. The IM team should be involved in this discussion, especially for published records. Also, in conversation with CIRMO folks we've been told to consider "data documentation" as **unscheduled** records, which means they can't be deleted without the approval of the government Chief Records Officer.

**Comment by CraigClark** [comment]
This feature is specifically for documentation. A permissions issue has been submitted, see #268

**Comment by CraigClark** [comment]
done, it's part of the creating an MR documentation, see https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/documentation/creating-and-editing-metadata-records

**Comment by CraigClark** [comment]
Assigning to @NicoledeGreef for review

**Comment by NicoledeGreef** [comment]
Looks good. Closing ticket.
