### ISSUE TITLE
Right-side column overlaps footer in MS Edge

### ISSUE THREAD

**Issue by ChristaBull** [bcgov/MFIN-Data-Catalogue#280]
**OP timer**

---

## Describe the bug
The content on the right-side column of the page continues through and past the footer in Microsoft Edge for Business, Version 120.0.2210.61 (Official build) (64-bit) which is the standard browser on B.C. government workstations.  Unsure if the issue is specific to the search page, or any page where the left-side content is smaller than the right-side.

## To reproduce
Steps to reproduce the behaviour:
1. Go to ['...'](https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/data-set?search_api_fulltext=tax)
2. Scroll down to footer
3. See error

## Expected behaviour
All content in the body of the page should push the footer lower so there isn't any overlap.

## Screenshots
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/141185297/047eb0d8-c6e7-4cbe-827b-9f43ced6411d)

**Comment by CraigClark** [comment]
Looks like something is out of whack in  twig template, I'll try to get to it this week, as soon as I'm done alpha stuff,

Blows up for me in firefox developer on mac when I select facets that shrink the results area

**Comment by CraigClark** [comment]
This was caused because an absolute positioning was used to move the sidebar up the page. Bootsrap layouts do not have a good solution for this while keeping elements in the right order. 

BS layouts have been replaced with css grid and it works fine.

there are two branches to make this work

base build branch https://github.com/bcgov/bcbb/tree/dc-280-layout-issue-on-search-results

bcbb theme branch https://github.com/bcgov/bcbb-theme/tree/dc-280-layout-issue-on-search-results

**Comment by CraigClark** [comment]
@lkmorlan could you please review/merge then this will be done

**Comment by CraigClark** [comment]
Fixed. tested with Edge on MS Windows 10
