### ISSUE TITLE
Information schedule display change/taxonomy addition: information schedule abbreviation

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#321]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

As a user I want the information schedule details to be more intuitive for me so that I can better understand the information schedule at a glance.

## Describe the idea
1) Add an information schedule abbreviation to the taxonomy, e.g. Property Taxation ORCS would have an abbreviation value of PTAX

2) Adjust the display of the IM classification code to use the Information Schedule abbreviation instead of the numeric code, e.g. PTAX-45000-03 instead of 160184-45000-03

## Actions

- [ ] Horray! I'm going to be a feature!

**Comment by CraigClark** [comment]
@mjmcclung The `schedule_number` field is a string, you could use PTAX instead of 160184 if you want to. 

If this is going to be something other than a number, you may want to consider a different label for the field. _Schedule code_ instead of _Schedule number_ for example.

**Comment by mjmcclung** [comment]
Wondering about the impact of this, especially given what is proposed in #322?

**Comment by CraigClark** [comment]
@mjmcclung There is no technological impact. It's just a string. It can be whatever value you want to use. The only reason it's a number is because the PDFs I was directed to as reference used numbers. I don't know about business impacts. 

#322 is a different thing. We will look into this one when we get to sprint planning. The columns of the importer use machine names, these are unaffected by field label changes.

Regards

**Comment by mjmcclung** [comment]
Ok, but if we change the column used to designate the parent (i.e. change from 'term name' to what is proposed in #322), then wouldn't there be ripple effects to existing Info Schedule taxonomies (i.e. existing terms might become orphaned)?  or maybe they just need to be deleted and reloaded?

**Comment by CraigClark** [comment]
@mjmcclung you are correct, those are issues to be discussed as part of #322. As for the field value, there is no issue using PTAX instead of 160184. That's just a field value and has nothing to do with the import other than the term it's associated with.

**Comment by NicoledeGreef** [comment]
@CraigClark is it feasible to add a _Schedule code_ in addition to the _Schedule number_ within the taxonomy?

e.g. _Schedule code_ would be PTAX
_Schedule number_ would be 160184

Then on display side, it would use the _Schedule code_ instead of _Schedule number_
The thought is that in the future we might need to use both in some way. When we're doing bulk loads it makes sense to load it as part of that effort.

In the Example below, ARCS is the _Schedule code_ and 100001 is the _Schedule number_

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/ac437036-7595-4a2d-9c62-9d8d4782ea31)

**Comment by CraigClark** [comment]
@NicoledeGreef I'm not sure how complicated that would get for the code that generates the IM Classification code, since it uses the same field. This is further complicate because ARCS uses the top level code and ORCs doesn't. Then arcs has a second level with no number, that seems to be for organizational purposes. We deal with this right now by saying 'if the lineage has a value in the `schedule_number` field, show it, otherwise do nothing. String all the terms in a lineage together and you get the IM Classification code.

I'm unclear, in the case of PTAX, I though that PTAX was replacing 160184. That's not the case?

**Comment by CraigClark** [comment]
If you look at [this example](https://test.cat.data.fin.gov.bc.ca/taxonomy/term/103/edit), I changed 10001 to ARCS in `schedule_number` and [it renders](https://test.cat.data.fin.gov.bc.ca/test-posted-user-1) the way you show above.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/4404a348-6fbb-4fdb-ba09-1390c8d7aa0f)

**Comment by CraigClark** [comment]
@NicoledeGreef we don't need to add the parents to the full name, parents are in the breadcrumb

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/cf54ed88-4c27-4056-ae48-6b56bbcc45ef)

**Comment by mjmcclung** [comment]
> @NicoledeGreef we don't need to add the parents to the full name, parents are in the breadcrumb
> 
> ![image](https://private-user-images.githubusercontent.com/3910508/297170095-cf54ed88-4c27-4056-ae48-6b56bbcc45ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MzQ3OTMsIm5iZiI6MTcwNTQzNDQ5MywicGF0aCI6Ii8zOTEwNTA4LzI5NzE3MDA5NS1jZjU0ZWQ4OC00YzI3LTQwNTYtYWU0OC02YjU2YmJjYzQ1ZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMTk0ODEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTRlNmNhNTk0OWUwYjRmODM1ZGFjZGUxNWVlMDI2YTNlMzVmYzFmM2I3ZmY0NTc2N2UwMDM4MTE1YWRhNTgwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IeIXdDIK869shzTyx0pEvUbyJNkek-gZlDt3UyqXZiw)

For educational purposes, the _Schedule full name_ needs to show more then just the last layer.  We don't want the users to have to look at the breadcrumb to get one piece of information and the display to get another.  We want them to see it all in one place to provide proper context.  That preferred place is in the display, not the breadcrumb.

**Comment by mjmcclung** [comment]
> If you look at [this example](https://test.cat.data.fin.gov.bc.ca/taxonomy/term/103/edit), I changed 10001 to ARCS in `schedule_number` and [it renders](https://test.cat.data.fin.gov.bc.ca/test-posted-user-1) the way you show above.
> 
> ![image](https://private-user-images.githubusercontent.com/3910508/297169382-4404a348-6fbb-4fdb-ba09-1390c8d7aa0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MzQ3OTMsIm5iZiI6MTcwNTQzNDQ5MywicGF0aCI6Ii8zOTEwNTA4LzI5NzE2OTM4Mi00NDA0YTM0OC02ZmJiLTRmZGItYmEwOS0xMzkwYzhkN2FhMGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMTk0ODEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWU0ZDU4MGRlMTg3OTNhYTI2YWQ2ZDkyZDc5ZTE1ZDc0MWU5NjljMTljZmUyNDJmN2YwYmEyNmYwOWE4ZWM5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._DGCBQlXwnlvte-F9PupxeH9k_SeOqC-v6jWXa88n1I)

Correct, but now we've lost the fact that 100001 is the ARCS Schedule number.  We would like to retain both pieces of information.

**Comment by CraigClark** [comment]
> For educational purposes, the _Schedule full name_ needs to show more then just the last layer. We don't want the users to have to look at the breadcrumb to get one piece of information and the display to get another. We want them to see it all in one place to provide proper context. That preferred place is in the display, not the breadcrumb.

@NicoledeGreef in that case, it's probably better to introduce code that shows the term lineage. There are other areas where we use the schedule full name for things like the `<abbr>` attribute.

**Comment by CraigClark** [comment]
> Correct, but now we've lost the fact that 100001 is the ARCS Schedule number. We would like to retain both pieces of information.

I get it now, what we need to solve then, is what constructs the IM classification code. Right now it's schedule_number. Mixing fields to construct this would be difficult.

Maybe a field for `schedule_code`, that gets used to construct the code viewers see on a MR view. Put whatever you want in there. 

Then on the term view, string together the `schedule_number`, the same way we do now. Or do we even need it strung together like this?

**Comment by mjmcclung** [comment]
Some clarifying comments:
- schedule code only applies at the higher level (i.e. at schedule level, i.e. PTAX level)
- primary code applies at the next level down (e.g. 45000) and secondary code (e.g. 03) at the level below that (for ARCS and ORCS)

If this field is being used for the **whole** information schedule taxonomy, regardless of level in the taxonomy, perhaps it's name needs to be made more generic ('_classification code_'?) for clarity and then we can address the specifics during display on the MR view.  The 'IM classification code' that is displayed would be a concatenation of all the _classification code_ s in the hierarchy together, separated by dashes.

Given this conversation, I am rethinking my previous wish to keep the schedule number (e.g. the 100001 value for ARCS).  If we are not using it in the short term, and not displaying it then why keep it?  What's the business value?  We are not developing a records mgmt system here (where an identifying number like this might have value), we are simply connecting records mgmt details to catalogue items.

**Comment by NicoledeGreef** [comment]
Agree - we are not building a Records Management system.  We are building a Data Catalogue. We want to allow users to enter **Information schedule** details as easily as possible so that it does not pose a barrier to Catalogue use, or to adherence to Info Mgmt practices. To do that we're employing hierarchical taxonomies, and nested taxonomy values in some cases (_record disposition_, _record life cycle duration_, and _record special flags_).

We have some field names in place currently and it is unlikely we can edit those at this stage in the game as there are downstream impacts (code dependencies).  What labels we show for these fields is relatively easily modified.  Adding a field is not likely a big deal if we need it (i.e. _schedule code_ in addition to _schedule number_).

Since _schedule number_ exists in the source system (EDRMS) there is no harm in storing it as part of the taxonomy. What the Catalogue does with the value is another matter.  If it's not needed for selection or display then we can suppress it from users' view.

I think it's better to have more details in place in case we decide we **_do_** need them for something, provided it's not a lot of extra work to prep/load or maintain.

I think #332 will help inform what we need and how we display it.

**Comment by mjmcclung** [comment]
Ok.  There are many different tickets related to Information Schedules now, each with their own dialog.  For this ticket, it sounds like we've landed with:

1. Keep _schedule code_ - use it to store the actual schedule number for ARCS, ORCS and Special schedules.  This will be stored but not made visible to the user at this time
2. Add a field called _classification code_ - use it to store the abbreviation, primary or secondary value (depending on the level of hierarchy) that will be concatenated together to make the 'IM classification code' that is made visible to users.

**Comment by NicoledeGreef** [comment]
closing this as #343 handles it
