### ISSUE TITLE
Switch field_modified_date to datatime type

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#324]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5858950905

---

## to duplicate

1. bookmark an MR
2. As a different user, update the MR and change the last update date, this should set the update flag for subscribed users
3. As the user from step 1 go to the dashboard
4. select 'all bookmarks' in the footer of the bookmarks section.
5. see that there is an updated badge beside the MR that was updated
6. click the link to view the mr
7. navigate back to the bookmarks page
8. see that the updated badge is still beside the record

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/6bbad84e-3995-4919-abe8-12f67e38f0bf)

## Expected behaviour

After I view a bookmarked record that has been updated, the update badge is removed

## Solution:
- [x] Remove `Date modified`  from section 2
- [x] Change the data type on `Date modified` to dateTime (from date)
- [x] Within the published dialog box on the Build page, add radios for Major and Minor updates. "this is a minor edit" and "this is a major edit (notify subscribers)"
- [x] On the node view, if `Date published` = `Date modified` then only display `Date published`
- [x] Only display the date for `Date modified` (not time)

**Comment by lkmorlan** [comment]
The problem is that `field_modified_date` stores the date, not the date and time. The date gets stored as noon on that date.

If I bookmark a record, it gets modified, and I visit it the next day, the "Updated" badge will disappear. If I visit in the afternoon of the date it was updated, the badge will disappear.

Options:
1. Make it work properly at the resolution of one day. In this case, if I visit today, _then_ you edit, it will not appear as updated.
2. Make `field_modified_date` be a date and time field. When it saves, if the date is today, save the current timestamp.

@CraigClark @NicoledeGreef please decide what you would like it to do.

**Comment by NicoledeGreef** [comment]
A lag of 1 day for the Updated flag to disappear is acceptable business-wise. No change needed. 

@CraigClark to discuss with @lkmorlan and verify what's happening before we close the ticket.

**Comment by CraigClark** [comment]
@NicoledeGreef Liam had some good ideas around this one. Lets talk at it at sprint planning tomorrow or at backlog refinement on Friday.

**Comment by NicoledeGreef** [comment]
There should be some indication that the minor edit and major edit radio buttons are a required field when publishing.

**Comment by lkmorlan** [comment]
@NicoledeGreef I have added a title to the major/minor radio buttons.
