### ISSUE TITLE
Data catalogue administrators cannot assign information management specialist role

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#330]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5868781676

---

As a data catalogue admin, I cannot assign the role _Information specialist role_.

I was going to fix this myself, however it looks like we are doing something custom with this so automated tests will run. I'll leave it to @lkmorlan .

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/6b2da543-1af9-4dd2-a2d1-e3121d71452e)

**Comment by lkmorlan** [comment]
The role permissions are added to `html/modules/custom/bc_dc/bc_dc.permissions.yml` so that during functional tests they do not raise the error "Adding non-existent permissions to a role is not allowed."

This did not happen with the `data_catalogue_information_management_specialist` role, but I added it anyway so that the permissions would appear together on the permissions page.

**Comment by CraigClark** [comment]
merged into 1.0.x
