### ISSUE TITLE
Information schedule term page and Metadata Record view

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#343]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5963753521

---

## Tasks

1. - [x] (Craig) create new text field field `field_classification_code`
2. - [x] (Liam) Use `field_classification_code` instead of `field_schedule_number` for the IM classification code on the Node view and the term view
3. - [x] (Liam) label term depths as per the screeshot on the term view. See note *schedule levels*.
4. - [x] (Craig) add *Information management details* as a pre-title on IM term pages

>[!IMPORTANT]
>
> ## schedule levels
>
>The terms have different functions depending on their depth. It is not the same for every schedule type
>
> ORCS level 1 (root) > Information schedule type
> ORCS level 2 > Information schedule name
> ORCS level 3 > Business function
> ORCS level 4 > Business category
>
> ARCS level 1 (root) > Information schedule type
> ARCS level 2 > *not used*
> ARCS level 3 > Information schedule name
> ARCS level 4 > Business function
> ARCS level 5 > Business category
>
> Special level 1 > Information schedule type
> Special level 2 > Information schedule name
>
> Unscheduled (root) > Information schedule type

>[!CAUTION]
> I have concerns about the robustness of relying on depth to identify the function of a term. Maybe an entity referce on the term would be a good idea. For example
>
> 1. create a vocabulary *information_schedule_function*
> 2. DC admin populates the vocabulary with labels
> 3. add a new field to the taxonomy *information_schedule_function* (optional) which is an entity referenced to the vocab
> 4. when creating/editing terms, DC Admin fills out the field
> 5. on the term page, crawl up the terms and if a field has *information_schedule_function* set, show the field as a label and the term as a value.
>
> This is just a thought
>
> Other option is we could discuss getting rid of level 2 for ARCS, I'm not sure how necessary it is. With it gone, we can restrict the vocab to 4 levels and everything would follow the same order.
>
## Background

Proposed modifications in this ticket with the intention to consolidate and close off #321 and #332. 
Note: we removed the headings on the Term page because the labels for each value clearly indicate the nature of the values and there is not enough info on this page to warrant subheadings according to UX best practices.  In the UX testing we will include scenarios that pertain to the IM section and adjust according to findings.

## On the Metadata Record screen

![IM_View](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/f74808cd-4912-476f-b938-ef40242711f6)

## On the Term page

![Term_View](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/f719f695-f055-4237-bf58-b4a800721adc)

## New field

1. Add new `field_classification_code` 
2. Use  `field_classification_code` instead of `field_schedule_number` for the IM classification code on the Node view

> Note: 
>  `field_schedule_number` will not be used at this time; we are maintaining the values for future use.

**Comment by NicoledeGreef** [comment]
@mjmcclung please review  changes for IM UI and field addition.

**Comment by mjmcclung** [comment]
Looks good with the exception of this comment:

> Note: we removed the headings on the Term page because the labels for each value clearly indicate the nature of the values and there is not enough info on this page to warrant subheadings according to UX best practices. In the UX testing we will include scenarios that pertain to the IM section and adjust according to findings.

Because of our low maturity in this space, there needs to be some sort of title on the page to give overall context as to what the user is looking at.  If we can't have subheadings then please remove the term name and replace with a single generic title at the top of the page (i.e. same title for any IM details page, regardless of the classification chosen):
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/2df9d66c-89a5-4750-9007-f73793d6de3d)

**Comment by CraigClark** [comment]
@mjmcclung @NicoledeGreef 

For accessibility/UX/SEO we don't want to have the same title on a bunch of pages on the same site.

What do you think of using a pre-title, like this:



![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/9a66e0c5-142f-4a27-a119-4a92c50c68b6)

**Comment by mjmcclung** [comment]
That could work, but user focus is still drawn to the larger font.  Can we increase the font of the pre-title and decrease the font of the actual title, or does this go against web design rules as well?

And just to clarify - when we talk about title - are we talking about the title used by the Drupal system, or the title that is displayed to users on the page?  Is it possible to have unique titles in the background, but the same title displayed to users (since the classification title is already represented in the 'Business category' section further down the page)?

**Comment by CraigClark** [comment]
The page title should look the same on every page. You want user's attention drawn to the large font (title). The same size/font/location on every page tells people 'this page is for …", this is the Gestalt design principal of repetition. If we make the _Information management details_ dominant at the page level, there is a high probability that anyone who has seen another info schedule page will leave, since the dominant visual marker is one they have seen already. I'm not sure about potential confusion over clicking on a link called _Reports and statistics_ and ending up on something where _Information management details_  dominates. 

Title is whatever goes into the title field of an entity, in the example here, that's _Reports and statistics not covered elsewhere_. This is mostly for Humans and anything else that reads the content. Search engines, feeds - whatever. As far as Drupal is concerned, _Reports and statistics not covered elsewhere_ is `/term/123`.

My recommendation would be to go with the pre-title as we have it here. It's a tried and tested pattern. Then, writer up a test case scenario where you would want the user to find information about the IM for a record. Test for accuracy and speed.

So it might be something like 'What is the business function of the information schedule on report X.' Then observe the journey. The UX team will know how to do this.

**Comment by mjmcclung** [comment]
Thank you for taking the time to explain this, it's very helpful in understanding the 'why' of differing perspectives.  My main concern was that some of the ARCS/ORCS titles are not descriptive enough (e.g. 'General') and neither do they describe the purpose of the page with all the other related information.  But, I agree with your recommendation.  And test cases can help us flush out whether it is having the desired outcome for the user.  Please proceed.  The fact that we have this information in the Catalogue at all is a huge step forward. :)

**Comment by NicoledeGreef** [comment]
relates to #353

**Comment by NicoledeGreef** [comment]
@CraigClark It looks like we have consensus on how to proceed here.

**Comment by CraigClark** [comment]
@lkmorlan please review/write tests/merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/343-field-classification-code

This adds the new field for `#1` above.

**Comment by CraigClark** [comment]
@lkmorlan please review/write tests/merge https://github.com/bcgov/MFIN-Data-Catalogue/tree/343-pre-title
This addresses `#4` by adding  field to the dc module settings page and displaying the value on information schedule terms as a pre-title

**Comment by lkmorlan** [comment]
I have put all the commits related to this issue on branch `343-information-schedule-term-page-and-metadata-record-view` and deleted the other branches. I will complete this issue on that branch.

**Comment by CraigClark** [comment]
@NicoledeGreef @mjmcclung We need some clarification.

We are trying to make sure the labels go with the correct level in the taxonomy.

here is the issue. ARCS and ORCS both have 4 levels in their vocabularies

ARCS works like this

```
- level 1 ARCS, has code , used in `field_schedule_code`
-- level 2, no code, just organizes the children
--- Level 3 has code, used in `field_schedule_code`
---- Level 4, has code, used in `field_schedule_code`
```

So an actual ARCS info schedule is `level 01`+`level 03`+`level 04`

So using the provided label structure, this would be

```
level 1 > Information schedule type
level 1 > Information schedule name
level 3 > Business function
level 4 > Business category
```

So ARCS (level 1) would be used twice because it is the schedule type and the schedule name, level 2 is ignored. I'm basing this on documentation the information I was sent where all ARCS schedules start with 10001



ORCS works like this


```
- level 1 ORCS, no code, it's the schedule type
-- level 2, has code, used in `field_schedule_code`
---  Level 3 has code, used in `field_schedule_code`
---- Level 4, has code, used in `field_schedule_code`
```


```
level 1 > Information schedule type
level 2 > Information schedule name
level 3 > Business function
level 4 > Business category

```

To help us figure it out, Please provide a map with labels for the 4 levels of ARCS and the 4 levels or ORCS

I would like something like this:

ORCS   
Information schedule type | level 1  
Information schedule name | level 2  
Business function | level 3
Business category | level 4

ARCS
Information schedule type | level 1  
Information schedule name | ??
Business function | ??
Business category | ??

**Comment by mjmcclung** [comment]
Hi Craig, yes you have it right.  I've included examples and field names in case it helps.

ORCS
Information schedule type | level 1 _(example: ORCS, from term **name** field)_
Information schedule name | level 2 _(example: Property Taxation, from **field_abbr_full_name**)_
Business function | level 3 _(example: Property taxation – general, from **field_abbr_full_name**)_
Business category | level 4 _(example: Property taxation data warehouse data, from **field_abbr_full_name**)_
IM classification code _(example: PTAX-45000-03, concatenation of **field_classification_code** from levels 2, 3, and 4)_

ARCS
Information schedule type | level 1 _(example: ARCS, from term **name** field)_
Information schedule name | level 1 _(example: Administrative Records Classification System (ARCS) Schedule, from **field_abbr_full_name**)_
Business function | level 3 _(example: Budgeting, from **field_abbr_full_name**)_
Business category | level 4 _(example: Budget files, from **field_abbr_full_name**)_
IM classification code _(example: ARCS-1000-20, concatenation of **field_classification_code** from levels 1, 3, and 4)_

If you need the same thing for the Special Schedules, just let me know.

**Comment by CraigClark** [comment]
@mjmcclung We should have it for all schedules, I don't want to make assumptions

**Comment by mjmcclung** [comment]
@CraigClark  Here is the map for Special Schedules.  We may choose to go one level deeper in the future but this depth is sufficient for now until we see how much use these schedules get.  Also, the deeper depths for these schedules don't conform to the same pattern as ARCS/ORCS so they will need more thought and research.

Special
Information schedule type | level 1 _(example: Special, from term **name** field)_
Information schedule name | level 2 _(example: Transitory Information, from **field_abbr_full_name**)_
IM classification code _(example: TRA, from **field_classification_code** at level 2)_

**Comment by NicoledeGreef** [comment]
Reviewed in dv14; @CraigClark to theme the elements before we close the ticket.

**Comment by mjmcclung** [comment]
The clickable business category link is missing.
Expected:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/c07549fc-6f03-45bf-b9d1-70ddc9beef13)

Actual result:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/a37f0c5d-9449-4004-90ec-f164a415b37c)

Also, on the details page, could we move the IM classification code up under the schedule information as expected?  Otherwise, it gets lost in the lifecycle details section.
Expected:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/df514c99-a852-4600-b9a8-70a4b9ea390f)

Actual result:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/e4d99adc-c5d3-445b-b8df-3693668554fa)

**Comment by CraigClark** [comment]
## To do 

### Change display on node view

@lkmorlan 

1. - [x] Get rid of the _IM classification details_ in the IM section of the sidebar
2. - [x] Add _Business category_ under _IM classification code_. This is the last level of the taxonomy. If the last level isn't selected, nothing should appear here.

Is should look like this

![IM_View](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/f74808cd-4912-476f-b938-ef40242711f6)

### Change position of the IM classification code

1. - [x] move the field for the im classification   code above the field set for the activity period etc and it should work.

**Comment by CraigClark** [comment]
This looks good to me. Tested on dv14, @NicoledeGreef could you please review and close.

**Comment by mjmcclung** [comment]
This piece does not seem to have been actioned:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/b1af1366-28ae-4767-b8cd-df671a91fe61)
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/32eca8b0-cb40-420f-af86-26eb32c54eb9)


It should be located in the first section of text, not the bottom section:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/a3645bd9-a80a-406e-9168-ff2e112f77b4)

**Comment by lkmorlan** [comment]
@mjmcclung the above is now fixed on dv14.

**Comment by mjmcclung** [comment]
Looks good, thanks!
