### ISSUE TITLE
Add additional terms to the Record Life Cycle Duration taxonomy

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#353]
**OP timer**

---
@NicoledeGreef here's the list of terms to add to the _record life cycle duration_ taxonomy:

3m
6m
9m
18m
1y
2y
3y
4y
5y
6y
7y
8y
9y
10y
12y
15y
20y
28y
29y
50y
85y

**Comment by NicoledeGreef** [comment]
@CraigClark  - flagging for us to discuss on Friday.

**Comment by NicoledeGreef** [comment]
@CraigClark as discussed: 
- [ ] creation of new vocabulary and an entity reference
- [ ] remove **Extend active period** and **Extend semi-active period**
- [ ] add the new vocab to the documentation so that there are visual references to IDs

**Comment by NicoledeGreef** [comment]
The list provided has been added to the `field_record_lifecycle_duration` taxonomy.  For Info Schedule taxonomy file loading prep purposes, the term IDs can be found at the [bottom of this page](https://dv14.openplus.ca/documentation/information-schedule).

These values will be propagated to dev, test, and prod when we migrate the postgres DB to those environments.

**Comment by NicoledeGreef** [comment]
@CraigClark 

In the termID table within the documentation, is it possible to sort that as it is organized in the Taxonomy list? It seems to be sorting by numbers first then then alphas which means that all the values with '1' as the first character are showing up in the term ID first and are ordered by the next character, whereas in the taxonomy itself things are ordered by shortest to longest length (e.g. 3m ---> 85y):

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/3e738200-bdb7-4854-8dac-c85e357fd549)

**Comment by CraigClark** [comment]
@NicoledeGreef I'll look into it. Should be doable.

**Comment by CraigClark** [comment]
@NicoledeGreef I took a look at this. It is sorting alphabetically. The problem is these fields are term labels, so strings. Those are set to display alphabetically. Which it is doing. Chronologically _1y_ comes before _10y_, but alphabetically _10y_ comes before _1y_.

We could investigate a solution, maybe introduce a sorting field or something. Or maybe it's possible to have logic that does something like look for digits preceeding m or y, if it's a single digit, assume a leading `0`., then sort if it's m, then y, then everything else alphabetically.

That seems complex though for a value that is likely to get set once and never again. 

The term page will show in the order you create terms in, unless you rearrange them yourself. That order is manually set.

I played with different sorting, none are super useful for what you want to do. 


My recommendation is to deal with the defaults Drupal is providing. This a a helper list, in a `<details>` element in the third level of documentation. I don't think the order has much user impact.

**Comment by NicoledeGreef** [comment]
That's fine - just thought I'd ask. It's odd that it doesn't display in the order set in the taxonomy itself. Where applicable I manually manipulated the values to reflect chronology.

**Comment by CraigClark** [comment]
> It's odd that it doesn't display in the order set in the taxonomy itself.

That's because this is a Drupal view. It is a query that goes and gets info from the DB and displays it. In this case, it is looking for the vocabs I specified, getting a list of terms and IDs for each. Views doesn't actually know what the taxonomy module does with this data. Since it's a query, there isn't an option to manually arrange views. We can sort and filter pragmatically, views is very powerful that way. For that the taxonomy module is sorting is very limited. You can only sort manually, or alphabetically.
