### ISSUE TITLE
TOC causing errors

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#357]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6023041353

---

## Describe the bug

When saving a page that uses `[toc]`, I get the following error

```
Warning: DOMDocumentFragment::appendXML(): Entity: line 7: parser error : Entity 'nbsp' not defined in Drupal\toc_api\TocBuilder->renderContent() (line 90 of modules/contrib/toc_api/src/TocBuilder.php).

```

## To reproduce
Steps to reproduce the behaviour:
1. Go to https://dv14.openplus.ca/documentation/information-schedule , this page uses toc
2. click edit
3. See error at top of page and in the log

It's possible this is related <https://www.drupal.org/project/toc_api/issues/3412644>

**Comment by lkmorlan** [comment]
This is related to the Drupal issue mentioned. However, solving that is not trivial. I was able to solve it for this page by removing an `h4` element that contained only `&nbsp;`. A stray header like that should not exist anyway. If this is only caused by empty headers or stray trailing `&nbsp;` entities, then we should just remove those.

**Comment by NicoledeGreef** [comment]
Verified: No error when editing TOC in dv14.
