### ISSUE TITLE
Edit mode: existing links should more specifically point to HTML bookmarks

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#365]
**OP timer**

---
### Section 2: Description
 
The **more information...** link should point to the bookmark link for **Review interval**.
https://dv14.openplus.ca/node/23#review-interval

### Section 3: Utility
 
The **Read more** link should point to the bookmark link for **Personal information**.
https://dv14.openplus.ca/node/23#personal_information-01

### Section 4: Significance
 
The **more information…** link should point to the bookmark link for **Critical information**.
https://dv14.openplus.ca/node/23#critical-information-01

**Questions:** 
In **Edit** mode should virtually all of the fields have a link to the applicable documentation? For example: **Security classification** does not have a link currently.  Should consider **more information…** links on **High value info** and **Authoritative info** similar to **Critical information**.

**Comment by CraigClark** [comment]
@NicoledeGreef I made the decision on whether there should be a link or not based on if the docs help you make a decision about what goes in the field or not. Some of these are general info. For example, if you don't know the security classification of the item, there isn't anything in the docs that is going to help you.

I removed the anchors because they can be too easily changed in the docs as content gets updated, but not easily changed in field help text because that's config. I don't think liking directly to the anchor is necessary in this case because if it's a short page, it will be easy to find what you need. If it is a long page, `[toc]` provides an index at the top of the page contents.

If you think we need links to the anchors, I would wait until all the documentation is done and do it then.

**Comment by NicoledeGreef** [comment]
No anchors required, at least for now, because the docs are still in flux and the anchor IDs can change (toc puts a version number beside pre-existing links, for example).
