### ISSUE TITLE
Create Dependency Report by Source System

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#369]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

As a Data Catalogue user
I want to access reports
So that I can gain insights into the data holdings of the Ministry.

As the Ministry Data Officer
I want to access a report that will give me insights into the data holdings of the Ministry and their dependencies
so that I can use that info to determine scope and scale of potential impacts to data holdings in support of technology planning/maintenance activities in the Ministry.

## Describe the idea

There is a need to know asset dependencies by Source System. For now, it could be in report form, with CSV export to allow further analysis.  Format as described in the dataset dependency report in #208 is a good starting point.

## Actions

- [ ] Hurray! I'm going to be a feature!

**Comment by NicoledeGreef** [comment]
If we're talking about where assets are sourced from: currently, a user with the IM Specialist role has access to all published items (across all Orgs). They can search without supplying a search term and all results will be returned.  There is an ability to select all results and export these to CSV or Excel for further analysis.  `Source system` is one of the attributes that is included in the export.

We will revisit what reporting development needs are as we go forward but for now I am hopeful this will address this need in a general way.

**Comment by mjmcclung** [comment]
This works, but requires post-processing (e.g. create pivot table) to view results by source system.  If IMB is engaging clients/custodians in IM/IT projects/activities are we supplying the list of affected datasets to them?  As a custodian, they should have some visibility into their affected datasets.  Do we have a custodian dashboard in the works to capture this oversight need?

**Comment by NicoledeGreef** [comment]
No Data Custodian specific dashboard is currently in the works. We'll research Data Csutodian needs once they've had some exposure to being Data Custodians and an opportunity to practice working in the Data Catalogue.

A Data Custodian is a user that either belongs to a `Data catalogue editor` or a `Data catalogue manager` user role as well as an Organization.  Content can be restricted by Organization although this is not recommended across the board (we encourage "default to open" wherever feasible).

- If there is a significant system change planned, a super user (`Data catalogue admin` or `Data catalogue information management specialist`) should Search and generate a report to inform decision making and change management and distribute as necessary _because_ a super user can have visibility across all Orgs
- `Source system` is currently not a mandatory attribute and only applies to MRs where Type = Data
- All users can Search and refine searches based on many attributes including `Source system` in order to gain insights; can be exported and manipulated external to the Finance Data Catalogue
