### ISSUE TITLE
504 time out issues on all openshift environments

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#374]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6186888544

---

We are experiencing 504 gateway time out issues when working with large taxonomies.

This can be seen at https://cat.data.fin.gov.bc.ca/admin/structure/taxonomy/manage/information_schedule/overview

It also happens when we try to import the taxonomy.

I'm not sure if it is relevant, but you can get to the vocabulary using the taxonomy_manager module https://cat.data.fin.gov.bc.ca/admin/structure/taxonomy_manager/voc/information_schedule

**Comment by NicoledeGreef** [comment]
dv14 handled the load just fine but our Openshift environments timed out after 30 seconds and manifested the Gateway error.  Thankfully the loads did complete in our environments.  It just took a lot longer and we had to review to ensure all the records made it.

In dev:
ARCS details loads in about 6 minutes
ORCS details loads in about 20 minutes

In dv14, we don’t get a Gateway timeout error.
ARCS details loads in about 46 **seconds**
ORCS details loads in about **2 minutes 29 seconds**

**Comment by NicoledeGreef** [comment]
This has been optimized as much as possible in the OCP environments. Information Schedule taxonomy page (>2200) dies because it hits the database that many times. It's an edge case; this is documented in the Info taxonomy page and the workaround is to use the Taxonomy Manager instead of the default Taxonomy editor page.  

Quota resources need to be increased in Production as noted in the Tech Walkthrough.
