### ISSUE TITLE
Create UI for reviewing published revisions without making an edit

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#379]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6216011879

---
On the Build page, if a record is up for Review there is no obvious way for a an editor to approve the review without making an actual edit to expose the publishing dialog.

**Comment by lkmorlan** [comment]
What would you like it to do? When there have been no edits since the published version, there is the message "Latest revision is published." We could have it so that the box with this message has a button to record that a full review has been done and no edits are needed, perhaps "Full review completed; no changes needed". That is a bit long. It could have the "This is a full review" checkbox and the button read "Update" instead of "Publish" (if you click "Update" without checking the checkbox, nothing changes). Other ideas?

**Comment by NicoledeGreef** [comment]
We'll go with (2). The update button is disabled until they check the box "This is a full review."

**Comment by lkmorlan** [comment]
This is implemented on dv14. We can hide the "Update" button but we can't disable it because of this Drupal core bug:

https://www.drupal.org/project/drupal/issues/3354998

**Comment by NicoledeGreef** [comment]
reviewed on dv14
