### ISSUE TITLE
Allow related documents that don't have a URL

### ISSUE THREAD

**Issue by ChristaBull** [bcgov/MFIN-Data-Catalogue#402]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6378631118

---
## User story

As a metadata record creator/editor I want to be able to provide information about related documents that aren't on a website so that the information that is available is documented and people know where to find it.

## Describe the idea

Remove restriction on the document link field to allow locations on file servers, or LANs to be provided.

Currently the related documents associated with a metadata record need to have a URL to be added; however, in many cases the information is not available on an external website.  This may change over time (e.g. new PIAs end up on a SharePoint) but it doesn't respect our current state.

>[!NOTE]
> This should be done with #419

**Comment by CraigClark** [comment]
@NicoledeGreef what patterns would be used here? Also, if we make changes here, we should change the help text too

**Comment by NicoledeGreef** [comment]
Relates to [#295](https://github.com/bcgov/MFIN-Data-Catalogue/issues/295#issuecomment-1986589358)

We'll look at identifying the patterns.

**Comment by NicoledeGreef** [comment]
@CraigClark @lkmorlan here are the general patterns as to what should be accepted for links:

Fileshares:
`\\fs1.fin.gov.bc.ca\FIN_DATA_SHARE_DOCUMENTATION\file_name.pdf`

URLs:
`https://bcgov.sharepoint.com/sites/FIN-ISP/Lists/Ministry%20of%20Finance%20PIAs/Attachments/759/FIN24019%20IMB%20-%20Finance%20Data%20Catalogue%20-%20Final%20signed.pdf?web=1`

Share drive locations:
`\\sfp.idir.bcgov\s105\S05016\Info Tech\Support Documentation 6450-80\FIN-Finance Data Store\Finance Data Store - Data Catalog.docx`

*After discussing it with some business reps we determined that mapped drive references are OK to include. Ideally these should not include letters though and **Related documents** must be suppressed for non-authenticated users. 

It is recognized that whether or not an interested party's mapped drive is equivalent to the MR editor's mapped drive could be an issue. IMB as default LAN based on a letter (some users may lost and re-map the same or another letter) and there are lettered LAN drives for different business areas; access is granted on an as needed basis. Using a network drive location instead of a letter will cut down on issues stemming from discrepancies of mapping to a letter. This may be an education piece for some users.

e.g. \\sfp.idir.bcgov\s105\S05016\Info Tech\Support Documentation 6450-80\FIN-Finance Data Store\Finance Data Store - Data Catalog.docx
instead of J:\Info Tech\Support Documentation 6450-80\FIN-Finance Data Store\Finance Data Store - Data Catalog.docx

If an interested party can't resolve the link and believes they need it, they will have to reach out to the point of contact for the MR to determine what the issue is and what is feasible.

There was a suggestion that **Related documents** could be shown on a separate view rather than in the sidebar.  This is something we can look out for in user testing but we are not prepared to change that at this point in time.

**Comment by CraigClark** [comment]
This should be done with #419

**Comment by NicoledeGreef** [comment]
Reviewed at: https://dv14.openplus.ca/node/37 which was a metadata record with 3 related docs defined prior to this enhancement.

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/bb2edef4-a287-4b5b-9bd4-3ca2fc1cf096)
![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/8307c3d8-8eb9-47f8-b98e-45582da428de)
![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/a20d238e-afcb-490e-b35f-926a30110f72)

The live view of the record displays the content as:
![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/bd8965df-fc43-4d31-b9aa-20c8dbc45a83)

One thing I did encounter was: after I added the PIA doc link and title and tried to Save I was prevented from doing so because the form expected all three related documents to have a doc link value. _Perhaps we should consider make the doc link a non-required value._

It's unfortunate we cannot make live links to fileshares but I suppose copy/paste is fine for the users that can see it and need to refer to the documents. Would be nice if all the docs were web enabled some day so we can get around this security related browser limitation.

@ChristaBull please review and let me know if you have any questions or concerns about present state of delivery on this item.

**Comment by NicoledeGreef** [comment]
@lkmorlan is going to move **Related documents** content under the **Data usage** section as a details element which will allow us to keep all the details available for consumers but will keep it initially hidden from the screen until the icon is clicked, similar to **data lineage**. 

This is an interim, compromise solution compared to where we are at currently and the significant amount of build and test required to implement a separate page.  Unlike Information Management, which is a taxonomy, there is custom work involved in creating a separate page to display. That is not an investment we can afford to make at this time.

Recommend revisiting this in the future to see if and how **Related documents** is being used post-launch.  Also, if the related docs info assets were http or ftp enabled we'd be able to keep things much more succinct.

**Comment by CraigClark** [comment]
The `<details>` element should look like this

closed



![details closed](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/a7ef2a2d-c46c-4312-82e7-8199eaee7302)

Open



![details open](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/b595e108-2363-44e6-b8c5-4d2d3ff10c6a)

**Comment by CraigClark** [comment]
@NicoledeGreef 

Liam has done this, we were thinking this could be enhanced by adding some HTML and tweaking some css

We could make it look like this using `<code>` tag

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/91bcda33-d8f0-48cb-a537-9cfa984550bd)

We could also get rid of all the wrapping using `<pre><code>`, it looks nicer, but unless you know to click three times or drag to select, you may miss copying the whole link **Example is in the second  privacy impact assessment**



![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/fd4000a7-a39b-466e-acd4-2937d28259e6)

Please let me know if you would like either of these changes and we will do a build of all we have so far.

**Comment by NicoledeGreef** [comment]
I think the code tag for non HTTP links is a good idea, given the current state of where docs are stored. I don't really like the pink colour but that is probably easily changed?

**Comment by CraigClark** [comment]
@NicoledeGreef That's the standard code colour, but we can change it when used in this instance. What colour would you like?

**Comment by CraigClark** [comment]
Also, to confirm, its the colour/font you want changed. Not the `<pre>` which would keep it all on one line but side scroll.

**Comment by NicoledeGreef** [comment]
> @NicoledeGreef That's the standard code colour, but we can change it when used in this instance. What colour would you like?

How about dark gray?

**Comment by NicoledeGreef** [comment]
> Also, to confirm, its the colour/font you want changed. Not the `\<pre\>` which would keep it all on one line but side scroll.

I think it should wrap.

**Comment by CraigClark** [comment]
> How about dark gray?
I'll find something dark, but light enough it looks different from the other text

**Comment by NicoledeGreef** [comment]
looks good
