### ISSUE TITLE
Critical information more info link not pointing to related content

### ISSUE THREAD

**Issue by ChristaBull** [bcgov/MFIN-Data-Catalogue#403]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6378665786

---

## Describe the bug
Clicking the more information link doesn't immediately direct to more information about what critical information is.

## To reproduce
Steps to reproduce the behaviour:
1. Go to Catalogue 'Dashboard'
2. Click on 'Build' for a metadata record
3. Scroll down to 'Section 5: Significance'
4. Click on 'more information...'

## Expected behaviour
When clicking on the more information link the user should be directed to where the critical information is explained (i.e. #critical-information).

## Additional context
There is a lot of content on the Metadata fields page users are directed to for more information about 'Critical information' that has nothing to do with critical information.  Placing the user at the top of the page increases the potential for users to be overwhelmed or confused.

**Comment by CraigClark** [comment]
@ChristaBull thank you for raising this. The issue here is that the help text on a field is config, so gets deployed as code. The content it links to can be changed by the data catalogue administrator. Because this page has so much content, we use a table of contents which is auto generated and assigns an ID to whatever the heading is. So if we link the help text on the field to `node/23#critical-information` and someone changes the heading from _Critical information_ to anything else, the link will break.

@NicoledeGreef 

I think this is a valid issue, the fields page in the help guide is long and people skim content. Off the top of my head, we could change the help text on the field to make it clear people will have to find the info they want on the page. ie:

> See the _Critical information_ section on the [Metadata fields](https://cat.data.fin.gov.bc.ca/documentation/metadata-fields) documentation.

Another thing we could do is break up the fields so you have a page for each field. They you could link directly to a field's page. We would need a parent page, the structure would look like this:

```txt

Documentation
    - Working with metadata records
       - Metadata record fields
            - field 1
            - field 2
        - Data dictionary fields
            - field 1
            - field 2

```

**Comment by NicoledeGreef** [comment]
@CraigClark please proceed with breaking out the docs into distinct pages. We will need to update the `more info` links as well.

**Comment by CraigClark** [comment]
Resolved with work done in #421

**Comment by NicoledeGreef** [comment]
need to review in Production because the live Docs are in Prod and it's a relative URL

**Comment by NicoledeGreef** [comment]
reviewed in Production
