### ISSUE TITLE
Keep newlines when importing data columns

### ISSUE THREAD

**Issue by ChristaBull** [bcgov/MFIN-Data-Catalogue#407]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6379005677

---

## Describe the bug
If a CSV contains newline characters it is replaced with a space when the file is imported.

## To reproduce
Steps to reproduce the behaviour:

1. Go to Catalogue 'Dashboard'
2. Click on 'Build' for a metadata record
3. Scroll down to 'Section 6: Data dictionary'
4. Click on 'Edit'
5. Click on 'Import/export data columns'
6. Import CSV with contents below and click 'Upload'

```
column_allowed_values,column_data_quality,column_description,column_name,column_size,column_transformations,column_type,instance_of,metadata_type,provenance_field_name,provenance_field_number,provenance_field_question,provenance_form_name,provenance_form_number
,"Some content on the first line.

More content on a 3rd line.",A unique system identifier for each Transparency Report submitted or updated by a reporting body or the Land Title and Survey Authority (LTSA),report_key,,,bigint,,,,,,,
```

7. Click on 'Import'
8. Scroll down to 'Section 6: Data dictionary'
9. Click on 'Edit'
10. Click 'Edit' next to the 'report_key' column
11. Scroll down to 'Column data quality' field
12. See error

## Expected behaviour
Column data quality column value should contain newline characters in CSV file.

## Screenshots
What was uploaded
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/141185297/5cf5bbe6-3aa8-4e75-adf5-591f0c2731e7)

After upload
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/141185297/6b0264bd-b06f-40c1-bfdd-19f86b41d4b8)

**Comment by CraigClark** [comment]
This isn't exactly a bug. The text areas use HTML for the input. This allows for some limited formatting. So if you import html, you output html. 

This is from a cell in an excel spreadsheet, column `column_allowed_values`:

```html
<p>this is a line.</p><p>This is a new line.</p><p>Here is a question. If we are going to have html in wysiwyg editor, should the csb output be html? Thay will make moving content around easier, but it will make the exported content less human readable.</p><p>add another paragraph in the excel file.<p><p>This one uses a br <br> for a line break</p>.
```

when it's imported, it looks like this:

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/1711f422-e759-4a26-8733-558a4c79e8cc)


This raises another question.

Do you want HTML in text area fields in the data dictionary?

Advantage is that you have some formatting abilities. Disadvantage is that when you import, you either need to go in after and format or your input has to have html. `<br>` would work for a line break.

Currently, when you download a data dictionary, text areas include the html. Whether that's good or not depends what you are doing with the spreadsheet. If your are importing into a system that understands html, this is good. Otherwise it makes it less readable for people.

If you want to keep HTML, I think there is a way to strip it from the export, but you would still need at least the `<br>` on import of you want line breaks.

@lkmorlan any thoughts on this?

**Comment by lkmorlan** [comment]
We could write an import filter to covert linebreaks to `br` elements.

**Comment by NicoledeGreef** [comment]
@lkmorlan - can we do a filter for the import and strip the HTML from the export?

**Comment by lkmorlan** [comment]
If you don't want HTML, the type of the field should be switched to plain text. Or do you want HTML on the system but not in exports?

**Comment by NicoledeGreef** [comment]
Let's go with: if there are breaks in the original import, insert `<br>` tags. Leave as HTML for export.

**Comment by CraigClark** [comment]
Tested and passed on dv14
