### ISSUE TITLE
Ability to report on Information Schedule details

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#448]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6528055542

---

- [x] add the IM additional details (Active period, Semi-active period, and Final disposition details) in the Report Builder export file

## User story

As a Ministry Data Officer
I want a report showing the landscape of IM retentions and classifications used for ministry data
so that I can assess data as part of projects and IM strategic planning.

## Describe the idea
The main search, with export capability, does not include any of the retention details in the export.  Only the information_schedule field is included, which is the lower level of IM classification.  No retention details or IM classification info are included.

In addition, the report builder includes the IM classification code, but does not include any of the retention details.

## Actions
1) include the _IM classification code_ as part of the export for the main search.
2) can the _information_schedule_ column be renamed in the export file from the main search?  This is not the information schedule, but rather the details of the lowest level of classification.  Perhaps _information schedule details_ could be the column name to reflect the column content?
3) include the Active period, Semi-active period, and Final disposition details in the Report Builder export

**Comment by NicoledeGreef** [comment]
We are not including the lower level IM details in the Search results because it includes only what is on screen when a user looks at the main metadata record page.

The renaming is not possible without custom code and in fact are what are called "machine names" in Drupal.  Labels change but field names do not so consistency is possible with machine names but not labels. If you wanted to compare exports over time, you might have an issue in using labels.

We can look at adding the IM additional details (Active period, Semi-active period, and Final disposition details) in the Report Builder export file.

**Comment by mjmcclung** [comment]
> We are not including the lower level IM details in the Search results because it includes only what is on screen when a user looks at the main metadata record page.

Lower level details are already included:
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/e996e8c9-9381-4774-a522-f10b213a4db7)

Is it possible to add the _IM Classification Code_ details as well to put the lower level details into context?
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/30302213/dd368307-8a1c-4ab1-aa1a-b756215dbb7f)

**Comment by CraigClark** [comment]
@mjmcclung Anything is possible, however complexity varies. The  export search exports the fields on the metadata record. 

The IM classification code is not a field on the record, its a field on the Information schedule that we are displaying on the record view. As far as the record is concerned, the only thing it knows is that it's `information_schedule` value is _Lists, spreadsheets and registers_. All the other IM related things are value of _Lists, spreadsheets and registers_, not the record, if that makes sense.

The record view is saying:

> Hey there Craig's Test Record, I see that your `information_schedule` value is _Lists, spreadsheets and registers_. Since I have that value, could you please go see what the root term is for `information_schedule` and display it with a label **Information schedule type**? While you are at it, it seems that _Lists, spreadsheets and registers_ is the last term in the hierarchy. Since that's the case, I know _Lists, spreadsheets and registers_  must have a classification code, please show me that too.

The search export is no where near as clever. It's saying 

> Oh, you are exporting a bunch or records? Let me go grab whatever values are assigned  in its fields  and give you those.

To get the IM code would require custom code, we would need to test that schedule field is the last term, since you can successfully submit a partial IM value, you could end up with a value that makes no sense.


For now we will get the Active period, Semi-active period, and Final disposition on the report builder. Since the report builder can be used by any authenticated user, that should help with the reports.

@NicoledeGreef , while looking into this I noticed there are a lot of fields missing from the export that we have added since search was build. I'll add a ticket for that

**Comment by mjmcclung** [comment]
Thanks for your explanation @CraigClark, it makes sense.

For now, let's focus on the report builder piece.  We can circle back to the search export at a future date if there is additional interest from business areas.

**Comment by lkmorlan** [comment]
@NicoledeGreef are the items now shown under "Actions" what you would like to have done for this? How does this relate to #449?

**Comment by mjmcclung** [comment]
@lkmorlan - it's just this piece that needs actioning (represented at the very top of the ticket):
- add the IM additional details (Active period, Semi-active period, and Final disposition details) in the Report Builder export file

This would add new items for the Report Builder, in addition to the _IM classification code_ that already exists.  #449 is a bug with the existing _IM classification code_ and a separate issue.

**Comment by CraigClark** [comment]
@lkmorlan we need the Active period, Semi-active period, and Final disposition added to the results table. Getting it there will make it available to the csv download. Put them immediately after the IM code. We will need to combine fields for Active and semi active periods. I forget the specific names for the fields, but active period, for example, is _Active period_ combined with _Extend semi-active period_ so you get something like _CY+7y_.

**Comment by NicoledeGreef** [comment]
Verified in dv14, the attribute values for Active, Semi-active and Final disposition have been added to the Report builder output and CSV download file:

snippet from on screen
![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/7e10e5ed-374f-4758-a9f1-6d28ab491996)

snippet of filtered for values in Excel containing 'FY':
![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/6f1a52df-7d33-45ac-9536-36b485284db6)

CY+test looks like a weird value but that is just symptomatic of some junk data value in dv14:
https://dv14.openplus.ca/admin/structure/taxonomy_manager/voc/information_schedule
