### ISSUE TITLE
Only admins, managers and editors should see environmental indicators

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#480]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6655028888

---

Currently any authenticated user sees the environment indicator at the top of the page. This could be confusing for IDIR users who don't do anything other than use the catalogue. Typically, these users won't know that test and dev exist.

Only DC admin, DC manager, DC API user and DC info specialists should see indicators.

This can be done on the permissions page.

## Nice to have

config split so that any authenticated users see test and dev indicators, on the odd chance they end up there. 

On prod Only DC admin, DC manager, DC API user and DC info specialists should see indicators.

I'm not sure if we are using config split. If not, I'm not sure it's worth it for this issue alone

## Todo
- [ ] Set `environment_indicator.indicator:name` to the empty string on prod.

**Comment by lkmorlan** [comment]
The environment indicator has been restricted to the roles shown above.

The nice to have features are more difficult because it is difficult to split permissions. Module `config_role_split` claims to do this; we have no experience with it. Another option would be to set the `environment_indicator.indicator:name` to the empty string on prod. This would allow the toolbar colors to display to those who have a toolbar, but would otherwise hide the environment indicator.

**Comment by lkmorlan** [comment]
@sylus Please set `environment_indicator.indicator:name` to empty string on prod. This is done in the settings file.
