### ISSUE TITLE
ampersand displaying as &amp; in the charts on Metadata Metrics report

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#494]
Visit the [Metadata metrics report screen](https://cat.data.fin.gov.bc.ca/user/2/reports).

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/0940c0d6-fd56-40fd-a21f-1f04e0e5be35)

**Comment by danhgov** [comment]
I found the bug, in the Charts module. I created an issue on their issue queue ([[HTML encodings (e.g. "\&amp;") showing up in legend](https://www.drupal.org/project/charts/issues/3456882)]), figured out where the fix was needed, and submitted an Merge Request in the issue for it to be pulled into the Charts module.

I've also added the patch from that MR into the composer.json for the DataCat, so that we can be using that patch already.

(While working on this, I saw that @lkmorlan also submitted issues for this same module, and was the last person to update the file that I updated. Small world.)

It's working on my localhost. Still need to push it up to github, and deploy it to dev.

**Comment by danhgov** [comment]
This was deployed in PR https://github.com/bcgov/MFIN-Data-Catalogue/pull/513

It is working on dev.

**Comment by danhgov** [comment]
I just realised that I had patched our code yesterday by linking to the merge-request I had made on Drupal.org for my patch to the Charts module. That does work, but the merge-request can be updated by other people, which could result in code we haven't tested ending up on our production server.

So I just added a simple patch file to a comment on the same issue, and linked to that as our patch. This change is in this PR: https://github.com/bcgov/MFIN-Data-Catalogue/pull/514

**Comment by danhgov** [comment]
@NicoledeGreef, this fix is deployed to Dev and Test, where it appears to me to be working. 

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/130506582/56a26ae1-27c6-4943-8ba0-ae0498500186)

Example URLS:

- https://dev.cat.data.fin.gov.bc.ca/user/136/reports
- https://test.cat.data.fin.gov.bc.ca/user/138/reports

**Comment by NicoledeGreef** [comment]
Reviewed in Test; checked pie chart label, Visibility, and Office of Primary Responsibility as they all tie into Organization. All good.

**Comment by chrislaick** [comment]
Deployed to PROD.
