### ISSUE TITLE
Resolve issue of backup PVC that is nearly full (again)

### ISSUE THREAD

**Issue by danhgov** [bcgov/MFIN-Data-Catalogue#498]
We have this PVC that is _almost_ at capacity, even though we just increased it last week.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/130506582/286eeb48-1f1f-4f1f-975a-589881be4156)

The obvious short-term solution is to simply increase it again, perhaps to 4GB. But we _just_ increased it from 2 to 3GB last week to resolve this same problem. What would be better would be for us to understand:
 
  - what is exactly is taking up this space?
  - how can we configure it differently to use less space for backups?
  - how would we even use these backups, in the case of a system failure?

**Comment by chrislaick** [comment]
@kardamk @danhgov and I had a meeting today and we increased the PVC to 4Gi as a temporary measure.

**Comment by chrislaick** [comment]
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/99423089/4988fe15-6a7f-45ce-b9cc-0ab93515d5be)
It is a little concerning seeing the utilization of the database backups PVC shoot up since last week of May, gobbling up all of the storage on the PVC.

*Ignore the turqouise line, as it represents utilization as a percentage. We have since increased the PVC 2Gi > 3 Gi > 4Gi.

**Comment by danhgov** [comment]
Thanks, @chrislaick. 
(BTW, I probably shouldn't have opened this ticket, as we already have https://github.com/bcgov/MFIN-Data-Catalogue/issues/497, which is a very similar topic.)

**Comment by chrislaick** [comment]
Closing ticket as this issue has been resolved in #497.
