### ISSUE TITLE
Documentation search

### ISSUE THREAD

**Issue by mjmcclung** [bcgov/MFIN-Data-Catalogue#500]
**OP timer**

---

## Describe the bug
Searching for the word 'type' in the documentation search area does not return the 'Creating a metadata record' page with includes the word 'type' 8 times on the page (I was searching to find out more information about the record type choice presented when creating a metadata record).

## To reproduce
Steps to reproduce the behaviour:
1. Click on Documentation
2. Type the word 'type' into the documentation search area
3. Click Search
[https://cat.data.fin.gov.bc.ca/documentation/search?search_api_fulltext=type](https://cat.data.fin.gov.bc.ca/documentation/search?search_api_fulltext=type)

## Expected behaviour
The search results should include the 'Creating a metadata record' page.

**Comment by NicoledeGreef** [comment]
@CraigClark is it possible certain pages aren't being indexed for the Docs search? The page noted by @mjmcclung consistently fails to show up in search results. One odd thing I noticed was that [the page](https://cat.data.fin.gov.bc.ca/documentation/creating-metadata-record) has only two revisions that are attributed to me. I find this improbable because of the complexity of the page content - I am certain you would have worked on it (nicely annotated screenshots, etc.)

**Comment by chrislaick** [comment]
@NicoledeGreef @mjmcclung I think this is no longer an issue. When I search "type" in the Documentation search, I see "Creating a metadata record" is the first search result. Can you please verify?

https://cat.data.fin.gov.bc.ca/documentation/search?search_api_fulltext=type

**Comment by NicoledeGreef** [comment]
@chrislaick Doc search does seem to be returning all hits for "type" now,
