### ISSUE TITLE
Think Aloud feedback: Enhance the login page so that it is more user friendly

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#507]
The login page is quite sparse. Let's explore some ways to make it more user-centric (less utilitarian).

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/cb8f7d35-172b-4ca6-9a43-a34ec168a6a0)

**Comment by NicoledeGreef** [comment]
We held a brainstorming meeting to illustrate the path of when a user might encounter the login page. A catalogue user would land on the login page if they weren't already authenticated to single sign on in their web browser and they were trying to access any page that isn't the landing page.

Examples of how this might happen: 

- Catalogue editor user gets an email due to their records being due/overdue for review
- Catalogue user subscribes a to a metadata record of interest and gets an email when that metadata record of interest has a significant update,

The links in the emails contain links to the login page which redirect to a node ID page. If they have already authenticated through SSO they page right through to the nodeID page, but if they have not yet authenticated they land on the login page.

The links are structured as:
`http://cat.data.fin.gov.bc.ca/user/login?destination=/node/<nodeID>`

The other time a user might land there is of they go there intentionally to log in as a Drupal user (for testing or administrative purposes, for example).  Example: http://cat.data.fin.gov.bc.ca/user/login?showcore

How do we make this login page more user friendly?
Ideas from the session: 

- Take the gin theme approach: super simple; include nothing but the bold call to login; omit other text links, images, search boxes, etc.
- Dress up the current login page to mimic the landing page: http://cat.data.fin.gov.bc.ca
- Question: if they're coming from the email links, can we click the login button for a user so they don't have to interact with the login button, they only need to supply credentials?

Let's take the gin theme approach and look into the javascript question.

**Comment by danhgov** [comment]
@NicoledeGreef, I'm quite sure I could set up auto-login, if you wanted. The rule would be:

- You are on the `/user/login` page (including `/user/login?destination=/node/1234` types of pages)
- There is only one login method available, "Log in with IDIR"

I'd suggest that the auto-login would add a message to the screen, saying "authenticating you with your IDIR" or something like that. Because I think that the idea of making people click that button is that _they_ are making the choice to use their IDIR to log in to the website. If we're going to auto-click it for them, we should at least let them know what is happening. And possibly also give them an informational banner-message on the page they land on, back on the drupal site, that "You have been authenticated using your 'firstname.lastname@gov.bc.ca' IDIR account.

And if ever we add a second authentication option besides IDIR, then the auto-login would no longer make sense, as we wouldn't want to decide on behalf of people which method they should authenticate with.

With those caveats, yes, we could make some javascript to auto-login people when they click a link in their email.

**Comment by chrislaick** [comment]
This is now working. When a catalogue user is not logged in and visits `/user/login?destination=/node/1234` the login process is automatically started and they go straight to SSO. The only exception is the `?showcore` parameter, which still works and is useful for test accounts.

**Comment by chrislaick** [comment]
Deployed to DEV and TEST.

**Comment by NicoledeGreef** [comment]
Reviewed in Test.

The email links with the destination parameter are handled so that the user is put to SSO if not already logged in; they supply their MFA code and are redirected to the appropriate node screen.

If a link is shared between users such as https://test.cat.data.fin.gov.bc.ca/node/62 which has visibility set to All IDIR and thus requires a login, user gets a page not found:

![Image](https://github.com/user-attachments/assets/c688b0f5-c759-4dd2-8ff3-15dd12af8fa8)

Can we push them to SSO as well?

**Comment by chrislaick** [comment]
I recommend in this case, we switch back to enabling Access denied 403 errors (removing the 403 to 404 redirect), and instead provide login options / auto-login when access is denied.

Otherwise the process gets quite complicated:

Access denied 403 > (Redirect) Page not found 404 > (check if exists and if so, proceed to login, otherwise display 404). From a security standpoint, it's not really any more secure as a user will be able to deduce whether a page exists by starting the login flow vs. 404 page.

**Comment by chrislaick** [comment]
The auto-login has been deployed to PROD. Just needing to work on the 404 part of this ticket.

**Comment by NicoledeGreef** [comment]
Please proceed with "...switch back to enabling Access denied 403 errors (removing the 403 to 404 redirect), and instead provide login options / auto-login when access is denied."

**Comment by chrislaick** [comment]
403 redirect to 404 page not found functionality has been removed. Instead, access denied 403 redirects to the auto-login process.

Deployed to DEV and TEST.

**Comment by david-fong-bc** [comment]
Not sure if this is related to this ticket, but when I try to log out in DEV, I get taken to a microsoft page prompting me to select an account to sign out of. If I select my gov account, things go normally and I get signed out, and when I click to log in, I get the microsoft sign in page (I use the phone call authentication option because my phone is pretty old). But if I instead use the browser's back-history button, I go back to FDC, and if I then refresh, I'm logged out of FDC, but there's a red notification banner at the top that says "To log in to this site, your browser must accept cookies from the domain dev.cat.data.fin.gov.bc.ca.", and when I click to log in, a previous microsoft login is reused (I don't have to go through the phone call process).

That's in DEV. In TEST, when I click to log out, the redirect to the microsoft page to select a microsoft account to log out of fails. Instead of being taken to a microsoft page, I get taken to `https://test.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/logout?id_token_hint=...&post_logout_redirect_uri=https%3A//test.cat.data.fin.gov.bc.ca/`, and the page shows a message that says "Login Error: Invalid redirect uri".

Feel free to ping me on MS teams and I can show you over a call.

**Comment by NicoledeGreef** [comment]
If I go Incognito and login with a Drupal account whose Org is PTB only and then I try to access [this test record that is set up with Visibility set to FREDA](https://dev.cat.data.fin.gov.bc.ca/node/106), I reach the 403 page as noted above. The same occurs if I use: https://dev.cat.data.fin.gov.bc.ca/user/login?destination=node/106

![Image](https://github.com/user-attachments/assets/3df7a3d7-cf1a-4368-9992-eaed7c1225b1)


**Question** that might inspire a new ticket: Can we make the 403 page more user friendly? Perhaps with the look and feel of the site indicate to the user something along the lines of "Access denied. Your account permissions do not match the record you are trying to reach."

**Comment by NicoledeGreef** [comment]
> Not sure if this is related to this ticket, but when I try to log out in DEV, I get taken to a microsoft page prompting me to select an account to sign out of. If I select my gov account, things go normally and I get signed out, and when I click to log in, I get the microsoft sign in page (I use the phone call authentication option because my phone is pretty old). But if I instead use the browser's back-history button, I go back to FDC, and if I then refresh, I'm logged out of FDC, but there's a red notification banner at the top that says "To log in to this site, your browser must accept cookies from the domain dev.cat.data.fin.gov.bc.ca.", and when I click to log in, a previous microsoft login is reused (I don't have to go through the phone call process).
> 
> That's in DEV. In TEST, when I click to log out, the redirect to the microsoft page to select a microsoft account to log out of fails. Instead of being taken to a microsoft page, I get taken to `https://test.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/logout?id_token_hint=...&post_logout_redirect_uri=https%3A//test.cat.data.fin.gov.bc.ca/`, and the page shows a message that says "Login Error: Invalid redirect uri".
> 
> Feel free to ping me on MS teams and I can show you over a call.

In Dev, I get logged out and returned to the home page.
In Test, I also see the "Invalid redirect uri" screen and it's consistent whether I am logged in as my IDIR account or my Drupal account:

![Image](https://github.com/user-attachments/assets/c09d8610-096f-4013-93b6-09e5560f1a5d)

**Comment by chrislaick** [comment]
Moving this back to In Development and looking what happened here.

**Comment by chrislaick** [comment]
@NicoledeGreef The logout behaviour has been fixed in TEST and PROD by reconfiguring the Common Hosted Single Sign-on (CSS) service. Logging out should now take you back to Microsoft to select an account to log out of, then kick you over to the home page of the Data Catalogue.

**Comment by chrislaick** [comment]
Set 403 Access denied path to front page and added error message "Access denied. Your account permissions do not match the record you are trying to reach."

Deployed to DEV and TEST.

![Image](https://github.com/user-attachments/assets/457a2086-1b0e-4f84-abca-7e6dea6c1a67)

**Comment by david-fong-bc** [comment]
@NicoledeGreef I just tested the various parts of this ticket over a call with Chris. The new behaviours and fixes Chris described above are all working for me, with only a minor oddity that the very first time I logout after this change is deployed, it logs me out without sending me to the microsoft page to select which microsoft account to log out of. Subsequent logouts all work as expected.

Can you let Chris know when this is ready to deploy to PROD?

Chris also noted that this issue has some relation to #573 and we did some testing for that too.
