### ISSUE TITLE
metadata metrics screen concerns

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#525]
When I log in as an Admin user, I have access to all content regardless of visibility restrictions; when I log in as a user that has no Organization membership applied to their profile I can only see content whose visibility is set to IDIR users; when I log in as a user that has one or more Orgs applied to my profile, I can see the content whose visibility is set to IDIR users and the content whose visibility matches my Org membership.

If I view the metadata metrics screen as each of these user types, I get the overarching view of the system's content at the top and it is identical for all of these users:

![image](https://github.com/user-attachments/assets/a702e8d2-db67-48f6-b0e1-aa3f512d6875)

Below that we have pie charts for Security classification and Visibility restrictions. For each of these users types the figures vary, presumably based on the user's profile. In other words, the figures are not based on the same number of records shown in the top block ("Published metadata records")
 
The pie charts for Security classification and Visibility restriction should also be based on Published records (not all records in the system). They seem to be when I look at the results as an Admin user. The **Records by security classification** percentages are as expected for the 31 published records in the system.

![image](https://github.com/user-attachments/assets/92609566-4610-4303-8e47-289b9251503d)

With respect to the **Records by restriction** pie chart, the percentages are not lining up, even for an Admin user, possibly because there is more than one restriction group applied to some of the metadata records.

If there are 31 published metadata records with visibility split as such (note the 9 records where there are 2 groups applied):

| Visibility restriction | Count | 
|------------|--------------|
| **Finance   Reporting & Enhanced Data Analysis, Information Management Branch** | 9 |
| IDIR users| 14 | 
| Finance Reporting &   Enhanced Data Analysis | 8 |

I would expect the following numbers, which don't match the pie chart:

| Visibility restriction | Count | Percentage |
|------------|--------------|-------------------|
| Finance   Reporting & Enhanced Data Analysis, Information Management Branch | 9 | 23 |
| IDIR users | 14 | 45 |
| Finance Reporting & Enhanced Data Analysis | 8 | 26|

I'm not sure what is happening to gather the **Records by restriction** numbers; as an Admin user, I think there is value is showing that x number of records have more than one visibility group applied so there is no need to split them out, double count if that is what is occurring.

**I think a metadata metrics report for Admin users that shows stats for content across all Orgs and visibilities makes sense and that was the original vision. Whether we should begin restricting it from the view of other user types is an outstanding question.**

**Comment by NicoledeGreef** [comment]
As discussed, let's remove access to "Metadata metrics" report from any roles that are not **Catalogue admin** or **Catalogue information management specialist**.

PO Action Item: spec out similar targeted metrics page for non-admin/IM users.

**Comment by danhgov** [comment]
Also, as discussed, lets concatenate any multiple-Visibilities into the pie-chart:

For visibility, it's not a radio-button set, but a series of checkboxes. If someone checks two or more, like this:
![image](https://github.com/user-attachments/assets/78b57c57-a5d3-4aa8-9f0e-46451f95c1ea)

... then we should be adding a new section to the pie-chart with both items concatenated together in the legend, such as "Finance Reporting & Enhanced Data Analysis **and**  Consumer Taxation Audit Branch". 

![image](https://github.com/user-attachments/assets/2e4ae024-100a-4adf-87aa-6b8435b65d61)

Many combinations should never happen, such as "Public **and** Property Taxation Branch". But if they do, it will be helpful for Nicole to be able to see them on that report, so that she can contact them.

That being said, @NicoledeGreef, perhaps we should simply put a form-validation rule, preventing people from putting illegal Visibility combinations in the first place. It could provide a helpful form-validation error message like "A record that is 'public' cannot also have 'Property Taxation Branch' visibility."

**Comment by NicoledeGreef** [comment]
The majority of metadata records should have visibility set to **IDIR users** or **Public** when they are ready for publication. 

If Public is selected, it should be the only selection in order to save.
If IDIR is selected, it should be the only selection in order to save.
I think we can allow other combos: FREDA & IMB, for example. In reality the use of values other than IDIR and Public should be few and far between and if admins see a lot of them or strange combinations it will be a flag to review/discuss.

**Comment by NicoledeGreef** [comment]
Closing this ticket and splitting into smaller tickets.
