### ISSUE TITLE
search results are not accurate

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#528]
## Describe the bug
When searches are performed the results are not including text matches in the title of the metadata record.

## Expected behaviour
Based on past discussion and [this ticket](https://github.com/bcgov/MFIN-Data-Catalogue/issues/303#issuecomment-1924477229), search results should be taking into account matches found in the title text as well as the description.

## Additional context
Example: in Test env there is a record titled "fruitsations test check"
https://test.cat.data.fin.gov.bc.ca/fruitsations-test-check

When you search for **fruit** or **fruitstations** the record is not returned. If you search for "test check" it is returned because those words also exist in the Description/Summary field.

This was first noticed in Production when searching for **bca**; the following records are not returned:
https://cat.data.fin.gov.bc.ca/bca-residential-property-inventory
https://cat.data.fin.gov.bc.ca/bca-commercial-property-inventory

CC: @ChristaBull

**Comment by danhgov** [comment]
I think I've solved this. In the search settings, it was very mysterious, because everything appeared to be configured correctly, including the "21x boost' that OP had given the title field. I reindexed it several times, and tried adding my own test record, which suffered the same problem as the Fruitsations.

Then I searched the Google, and found [this thread](https://www.drupal.org/project/search_api_solr/issues/3026374), suggesting "Are you using views? Did you add the filed to the list of fields to be searched there?".

And sure enough, we are using views. In [our site_search view](https://test.cat.data.fin.gov.bc.ca/admin/structure/views/view/site_search), there is this:

   ![Image](https://github.com/user-attachments/assets/928cc334-9830-4cb6-9151-e7386c955277)

... inside of which _was_ this:
   ![Image](https://github.com/user-attachments/assets/07f11767-a0bc-4366-87a9-de028e8c746e)
I have now unselected "Rendered HTML output" (which I think is the full rendered Node _minus the title_), such that it now searches "all available fulltext fields".

Et voila! [The Fruitsation search, on Test](https://test.cat.data.fin.gov.bc.ca/search?search_api_fulltext=fruitsation)
   ![Image](https://github.com/user-attachments/assets/4efdd36c-eb5d-47d3-af4b-7094fed7cc12)


If this seems to work correctly now in your opinion, @NicoledeGreef, I can make the same change directly on the prod server via the UI.

In the meantime, I've submitted a PR with the fix in it: https://github.com/bcgov/MFIN-Data-Catalogue/pull/531

**Comment by NicoledeGreef** [comment]
Great sleuthing, @danhgov Thanks!

The only thing I noticed was that searching for "fruit", "fruits", and "fruitsa" did not yield the Fruitsations record result. It did show up when I searched for "fruitsat"; does this mean there is a minimum character requirement for matches, I wonder?

**Comment by danhgov** [comment]
Moving this ticket back from "Done", as the PR is not actually merged yet.

**Comment by danhgov** [comment]
The PR for this ticket is now merged.

**Comment by danhgov** [comment]
@NicoledeGreef, this code is on dev/test now.

**Comment by chrislaick** [comment]
Deployed to PROD.
