### ISSUE TITLE
Make a support link always be available

### ISSUE THREAD

**Issue by david-fong-bc** [bcgov/MFIN-Data-Catalogue#555]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/Idea

---

## User story

As a user of the Data Catalogue, I would like to be able to easily reach a page/email where I can ask for support. There is a support link on the homepage (to email Nicole in the dev/test environments, and open JSM in prod), but if I have never used that support link before, I may not remember it exists at the moment that I am using the Catalogue and realize I want support with something.

## Describe the idea

Add a link to reach support that is available from every webpage in the website, such as in the site footer.

## Actions

- [x] Horray! I'm going to be a feature!

**Comment by NicoledeGreef** [comment]
For Production: let's change the footer **Contact us** link so that it reads "Contact Support" and links to https://fincsp.atlassian.net/servicedesk/customer/portal/12

For Dev and Test: let's change the footer **Contact us** link so that it reads "Contact Support" and links to Nicole's email address.

**Comment by danhgov** [comment]
This is similar to what we did in #516. We can use the same technique (getting environment from Environment Indicator).

**Comment by chrislaick** [comment]
This has been deployed to DEV and TEST, however it won't be ready to validate until it gets deployed to PROD, as it's a PROD-specific change.
