### ISSUE TITLE
I am not receiving emails for major changes to MRs I bookmarked

### ISSUE THREAD

**Issue by david-fong-bc** [bcgov/MFIN-Data-Catalogue#559]
## Describe the bug

I don't receive emails for major changes to MRs I bookmarked. I can reproduce this in the dev environment, and I have not tried in the test or production environments yet. This happens both for MRs that I created, and for ones I did not create.

I am logged in to the dev environment with my IDIR, "DAFONG", with email address david dot fong at gov dot bc dot ca (written weirdly here to hide from spam crawlers).

## To reproduce
Steps to reproduce the behaviour (for example):
1. Both Nicole and I bookmarked https://dev.cat.data.fin.gov.bc.ca/april-19-test, which is a MR she created with her IDIR account.
1. I edited it and published with major changes. Nicole got an email, but I did not (I refreshed outlook, checked my junk folder and did an inbox search, and didn't see it).
1. I made another edit and published with major changes again, and Nicole got an email, but I did not.

Nicole and I also tried with a MR I created, and a revision published by her, and I also didn't get an email for it. That was with https://dev.cat.data.fin.gov.bc.ca/node/156/revisions.

## Expected behaviour

I expected to get emails about published revisions for MRs I bookmark.

## Additional context

Here's a screenshot Nicole took from gcnotify that shows that emails were sent to her, but not to me:

![image](https://github.com/user-attachments/assets/ce3c81d1-b73a-4190-b798-bf741d418428)

**Comment by david-fong-bc** [comment]
@danhgov Can you take a look at this? We're wondering if it's just due to some intentional configuration for the dev and test environments. I can also reproduce in the test environment.

**Comment by danhgov** [comment]
Hi @david-fong-bc,

This is happening because on Dev & Test, the notification service (GC Notify) has been configured in "Test mode", which means that emails are not actually sent to people, unless they are on this safe-list:

* Chris Lai
* Nicole
* Myself
* craig@openplus.ca
* liam@openplus.ca
* william.hearn@gov.bc.ca
* sang@openplus.ca
* stephen@openplus.ca

@NicoledeGreef, I **have just added David** so that he can be part of testing, and removed all of the Openplus people (including Will Hearn) since their contract has been over for a few months now.

**Comment by david-fong-bc** [comment]
@danhgov Thanks for the info and the change! I just tested in the dev environment and I receive notification emails now.
