### ISSUE TITLE
Metrics and statistics - allow custodians to see datasets at a glance

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#60]
QUESTIONS:

1. Document what metrics and statistics to collect and display.
2. What about stars / flags / ratings?
3. What about noted issues?
4. Graphic for remaining time until refresh of metadata?

**Comment by CraigClark** [comment]
This is a bit confusing to me. Is this info I see when I look at a data set? or is it a display of several datasets and their status on a dashboard?

**Comment by NicoledeGreef** [comment]
This is a data provider's dashboard I think.  I'm not saying "Data Custodian" because a Data Custodian, by definition, is a responsible party for their work area's data assets as determined through legislation or policy however, they may not be the person logging into a data catalogue regularly to set up metadata records.

**Comment by NicoledeGreef** [comment]
There will be specific tasks for related features

**Comment by NicoledeGreef** [comment]
Closing this ticket because the intent is covered in other tickets (see #137)
