### ISSUE TITLE
Metadata record should have an immutable endpoint so that consumers / systems can link back to it

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#74]
**OP timer**

---

## User story

As a consumer of data that values its metadata,

I want to be able to easily reference the metadata through a URL that doesn't change over over time

So that anywhere I refer to the metadata record will stay current regardless of how the metadata values evolves.

## This feature support the following requirements

[alpha release](https://openplus.monday.com/boards/3958997205/pulses/4605939234) 

## Additional context

> **Note**: as meeting at #93 

The built in [Drupal node]((https://www.drupal.org/docs/core-modules-and-themes/core-modules/node-module/about-nodes) ID (NID) will be used as a unique identifier.

If at some point in the future there is a need to add attributes to the ID, the issue will be re-visited.

Paths in Drupal are aliases to the NID, ie `/node/1234`. If a user copies the link from the address bar and uses it in a system outside of Drupal, the link will always resolve even if the path changes.

There is currently a field for unique ID that needs to be removed from the data set content type. In the [architecture document](https://bcgov.sharepoint.com/:w:/r/teams/06981/Shared%20Documents/General/architecture/BC-MFIN-Content-Architecture-Living-doc.docx?d=wd7cd5a7fb8454ca29c882a17fe87b27f&csf=1&web=1&e=nmOP8y) make note in the unique id section that this is satisfied by the NID.

## Proposed solution

1. Remove `field_unique_identifier` from data set content type > @CraigClark 
2. Update architecture document > @NicoledeGreef 

## Estimated level of effort 

- less than 1 day

## Definition of done (DoD)
- [ ] `field_unique_identifier` no longer exists on the data set content type
- [ ] architecture type has been updated

**Comment by NicoledeGreef** [comment]
FYI: this immutable endpoint may tie in with the **Unique Identifier** core metadata requirement.

Unique Identifier should be immutable; every attribute value on an entity could change over time but it all tracks back to the ID; refer to https://www2.gov.bc.ca/assets/gov/government/services-for-government-and-broader-public-sector/information-technology-services/standards-files/311_core_metadata_guidelines.pdf

The ID value format should be what brings the business value.  The business, in this case, is likely more the IMB (Product Owner/System Builders personae).

**Comment by CraigClark** [comment]
PR submitted https://github.com/bcgov/MFIN-Data-Catalogue/pull/102

**Comment by NicoledeGreef** [comment]
At our July 17 meeting the team came to the conclusion that "UNIQUE IDENTIFIER" can be called anything; as per the Guidelines for the Core Metadata Standard we can come up with a MAP (Metadata Application Profile) and the documentation for the MAP can indicate that:

nodeID is an immutable unique ID that corresponds to a node (which is akin to a metadata record) and is readily available in Drupal. nodeID maps to the UNIQUE IDENTIFIER core metadata requirement.  

This is our MVP stance - if we need something different down the road we can pivot.

Example of an immutable end point using nodeID: https://dv21.openplus.ca/node/12/

We will not show a Unique Identifier in the metadata record:


![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/5fb9df97-ae49-4ba2-87eb-389d090207d6)

We should provide a way for the users to easily copy the nodeId based link so that they can paste elsewhere as needed.
The regular URL they see in the browser changes over time if the title field is modified. 
Example:
https://dv21.openplus.ca/data-set/property-transfer-tax-ptt

**Comment by CraigClark** [comment]
reopening until PR to get rid of field is merged.
