### ISSUE TITLE
Ability to contact someone who owns the metadata

### ISSUE THREAD

**Issue by sangtrinh** [bcgov/MFIN-Data-Catalogue#77]
https://github.com/bcgov/MFIN-Data-Catalogue/labels/stuck

pending client feedback

**OP timer**

---

## User story

As a user of the data catalogue, I want to know who to contact if I have questions about the data.

## This feature support the following requirements

[alpha release](https://openplus.monday.com/boards/3958997205/pulses/4605939234)

## Proposed solution

Using the existing `organization` vocabulary, create the following fields:

### Data custodian
field type:text
field machine name: data_custodian
field label:Data custodian
field values: user enters values
form display: text input
display: plain text
note: On form display, use help text ‘This is the position responsible for this data set, for example Assistant Deputy Minister, Executive Director, or Director’

### Additional information
field type:text area formatted
field machine name: information
field label:Additional information
field values: to be filled out by user
form display: text input area
display: text area
note: We may want to consider basic html for this so it doesn’t get ugly. Allow links, `<b><i><sub><sup>`. Also add help text 'Additional information about this OPR, for example the specific person to contact about a data sets the custodian is responsible for'

## Estimated level of effort

- 1 day

## Definition of done (DoD)
- [ ] admins can add a data custodian and additional info on fields the term
- [ ] editors selecting org on form populates the additional info and the custodian
- [ ] users can see the OPR, custodian and additional info on node view

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

**Comment by CraigClark** [comment]
IS this same as #30 ? @sangtrinh

**Comment by NicoledeGreef** [comment]
Data Custodian: taxonomy term called 'data custodian': position (Assistant Deputy Minister, Executive Director, Director, etc.)

pointOfContact: the most desirable person to reach to about the data (could be the same as Metadata Maintainer) but it's at the discretion of the business domain; open text fields for contact name/email

**Comment by CraigClark** [comment]
@NicoledeGreef 

before I get too far into this, is this the same thing as the office of primary responsibility? Could we extend that field to meet this requirement? see <https://bcgov.sharepoint.com/:w:/r/teams/06981/Shared%20Documents/General/architecture/BC-MFIN-Content-Architecture-Living-doc.docx?d=wd7cd5a7fb8454ca29c882a17fe87b27f&csf=1&web=1&e=lgDWgW>

we could do something like 
Office of primary responsibility is: 
The position responsible for data sets belonging to the office of responsibility is: 
Contact info for the office of primary responsibility:

**Comment by mjmcclung** [comment]
> @NicoledeGreef
> 
> before I get too far into this, is this the same thing as the office of primary responsibility? Could we extend that field to meet this requirement? see https://bcgov.sharepoint.com/:w:/r/teams/06981/Shared%20Documents/General/architecture/BC-MFIN-Content-Architecture-Living-doc.docx?d=wd7cd5a7fb8454ca29c882a17fe87b27f&csf=1&web=1&e=lgDWgW
> 
> we could do something like Office of primary responsibility is: The position responsible for data sets belonging to the office of responsibility is: Contact info for the office of primary responsibility:

OPR is the branch or business area responsible.
Contact should go to a specific person, ideally as someone listed on the metadata record.
Currently Data Custodians are at the Executive Director level, but this is under review.  Ideally we'd have the overarching person who is accountable (custodian) as well as a Subject Matter Expert that inquirers could contact.

There is a requirement in upcoming policy to identify Data Custodians and it will be prudent for those Custodians to identify a SME/contact but we don't currently have this structure set up in our Ministry.

**Comment by CraigClark** [comment]
@mjmcclung My understanding is that there are three people at play.

1. The custodian (a responsible person, but may not know about a specific dataset)
2. SME Knows about the source data that the custodian is responsible for
3. Data editor, the person who is adding/editing metadata in the data-catalog

`#3` is easy for now, that's the content creator and Drupal keeps track of that. 
`#2 `, I would imagine, is the person most people will want to contact if they need to know something about the data set.

How we manage `#2` needs to be carefully thought out. This person may or may not have a active account in Drupal.

What I'm wondering, is, would questions about data-sets belonging to an org unit, or a sub-unit or the org, always go to the same person. I'm imagining something like:

1. We create an entity called _Farms_. This is the Office of Primary Responsibility
2. _Farms_ can have sub categories, say _dairy_, _cash crop_, _poultry_
3. The Director of _Farms_ is the responsible person for all _Farms_ data sets, so the data custodian field says _Director of farms_
4. J. Doe is the SME for Dairy, J.Doe's name and email address goes in a contact field on _Dairy_
5. a data editor creates a data set record. one of the fields says OPR, so they select _Farms_ from a list, which exposes the sub orgs dairy, cash crop, and poultry. Data editor select dairy.
6. what gets rendered on the data set view is OPR=Farms, custodian=Director of Farms, Contact=J.Doe

If we do it this way, when J.Doe retires, we change the contact for _farms/dairy_ and all data sets are instantly updated.

In this example, I use sub units just because we can. If it works, we could have all _Farm_ requests go to J.Doe. 

would something like this work? What we are trying to do is keep it lean for data editors. So if there is a bunch of things we can populate based on the selected OPR, that's the best way to do it.

**Comment by mjmcclung** [comment]
Yes, this sounds like a reasonable approach, especially as a first iteration.  There may be nuances but this would be more than what we have now and a major improvement.
